//! Wire allowlister into OpenCode by writing its plugin shim.
//!
//! OpenCode has no subprocess hook: it gates a tool call only through an
//! in-process JS/TS plugin that blocks by throwing. So instead of merging JSON
//! into a settings file (as the other harnesses do), `init` writes a small
//! `allowlister.js` plugin into OpenCode's auto-loaded plugin directory. The
//! plugin spawns `allowlister hook opencode`, pipes each shell command as JSON,
//! and throws when allowlister denies it.
//!
//! The plugin is a generated artifact owned by allowlister: registration writes
//! the canonical content, leaving it untouched only when it is already identical.
//! OpenCode auto-loads any `*.js`/`*.ts` under the plugin directory with no
//! `opencode.json` entry, so dropping this file in is the whole wiring.

use std::fs;
use std::path::{Path, PathBuf};

use crate::errors::{Error, Result};
use crate::io::configfs::Env;

/// The command the plugin shim spawns, surfaced in messages.
const HOOK_COMMAND: &str = "allowlister hook opencode";

/// The plugin filename allowlister writes.
const PLUGIN_FILE: &str = "allowlister.js";

/// The plugin shim OpenCode auto-loads. A single named export (the loader scans
/// every export and rejects a non-function, so the file carries exactly one). It
/// gates on command *content* — any tool call carrying a `command` arg, which
/// covers the `bash`/shell tools across builds — and blocks by throwing, the only
/// block primitive `tool.execute.before` offers. It fails open: if the binary
/// cannot run or its output is unparseable, the command is not blocked.
const PLUGIN_JS: &str = r#"// allowlister OpenCode plugin — generated by `allowlister init --harness opencode`.
//
// OpenCode blocks a tool call only from an in-process plugin, so this shim bridges
// to the allowlister binary: before any tool runs it spawns `allowlister hook opencode`,
// piping the tool name and arguments as JSON, and throws to block when allowlister
// denies it. The Rust adapter routes a shell call to the command engine and every
// other tool (read/write/edit/webfetch and MCP `server:tool`) to the tool-rule
// engine. Edit your rules in .allowlister.json, not here; re-running
// init regenerates this file. Auto-loaded from .opencode/plugin/ (project) or
// ~/.config/opencode/plugin/ (global) with no opencode.json entry needed.

export const allowlister = async ({ directory }) => ({
  "tool.execute.before": async (input, output) => {
    const tool_name = (input && input.tool) || "";
    if (!tool_name) return;
    const args = (output && output.args) || {};
    const cwd = args.workdir || directory || ".";
    const event = JSON.stringify({ tool_name, tool_input: args, cwd });

    let stdout = "";
    try {
      const proc = Bun.spawn(["allowlister", "hook", "opencode"], {
        cwd,
        stdin: new TextEncoder().encode(event),
        stdout: "pipe",
        stderr: "ignore",
      });
      stdout = await new Response(proc.stdout).text();
      await proc.exited;
    } catch (_) {
      // Fail open: if the gate binary cannot run, never block the command.
      return;
    }

    const trimmed = stdout.trim();
    if (trimmed.length === 0) return; // no objection — let it run
    let decision;
    try {
      decision = JSON.parse(trimmed);
    } catch (_) {
      return; // unparseable output: fail open
    }
    if (decision && decision.decision === "deny") {
      throw new Error(decision.reason || "Blocked by allowlister");
    }
  },
});
"#;

/// Where OpenCode auto-loads plugins: `<config>/opencode/plugin/allowlister.js`
/// for the user (global) scope, or `<cwd>/.opencode/plugin/allowlister.js` for a
/// project (local) scope. The global config dir is XDG-aware (`$XDG_CONFIG_HOME`,
/// else `~/.config`), like allowlister's own.
pub(crate) fn settings_path(global: bool, cwd: &Path, env: &Env) -> Result<PathBuf> {
    if global {
        config_dir(env)
            .map(|dir| dir.join("plugin").join(PLUGIN_FILE))
            .ok_or(Error::NoConfigHome)
    } else {
        Ok(cwd.join(".opencode").join("plugin").join(PLUGIN_FILE))
    }
}

/// The user-global OpenCode config directory: `$XDG_CONFIG_HOME/opencode`, else
/// `~/.config/opencode`. `None` when neither is set.
fn config_dir(env: &Env) -> Option<PathBuf> {
    if let Some(xdg) = &env.xdg_config_home {
        return Some(xdg.join("opencode"));
    }
    env.home
        .as_ref()
        .map(|home| home.join(".config").join("opencode"))
}

/// What `register_hook` changed, for the user-facing summary and so tests can
/// assert idempotency (a second run rewrites nothing).
pub(crate) struct SettingsChange {
    pub path: PathBuf,
    pub created: bool,
    pub updated: bool,
}

impl SettingsChange {
    /// True when the plugin already had our exact content — a re-run that touched
    /// nothing.
    pub fn was_noop(&self) -> bool {
        !self.created && !self.updated
    }
}

/// Write the plugin shim at `path`, creating it if absent and rewriting it only
/// when its content differs from the canonical shim. Idempotent: an up-to-date
/// plugin is left untouched.
pub(crate) fn register_hook(path: &Path) -> Result<SettingsChange> {
    let desired = PLUGIN_JS;
    let existing = if path.exists() {
        Some(fs::read_to_string(path).map_err(|err| Error::Read {
            path: path.to_path_buf(),
            source: err,
        })?)
    } else {
        None
    };
    let created = existing.is_none();
    let updated = existing.as_deref().is_some_and(|e| e != desired);
    if created || updated {
        write_text(path, desired)?;
    }
    Ok(SettingsChange {
        path: path.to_path_buf(),
        created,
        updated,
    })
}

/// The hook command the plugin shim runs, for messages.
pub(crate) fn hook_command() -> &'static str {
    HOOK_COMMAND
}

/// The plugin source, for the `--no-hooks` manual-wiring path.
pub(crate) fn plugin_source() -> &'static str {
    PLUGIN_JS
}

/// Write `text` to `path`, creating the parent directory as needed.
fn write_text(path: &Path, text: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).map_err(|err| Error::Write {
                path: parent.to_path_buf(),
                source: err,
            })?;
        }
    }
    fs::write(path, text).map_err(|err| Error::Write {
        path: path.to_path_buf(),
        source: err,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn creates_the_plugin_file() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".opencode/plugin/allowlister.js");
        let change = register_hook(&path).unwrap();
        assert!(change.created);
        assert!(!change.updated);
        assert!(!change.was_noop());

        let text = fs::read_to_string(&path).unwrap();
        assert!(text.contains("allowlister hook opencode"));
        assert!(text.contains("tool.execute.before"));
        assert!(text.contains("throw new Error"));
    }

    #[test]
    fn re_registering_is_a_noop() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("plugin/allowlister.js");
        register_hook(&path).unwrap();
        let again = register_hook(&path).unwrap();
        assert!(again.was_noop(), "an up-to-date plugin is left untouched");
    }

    #[test]
    fn rewrites_when_content_differs() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("plugin/allowlister.js");
        write_text(&path, "// stale plugin\n").unwrap();
        let change = register_hook(&path).unwrap();
        assert!(!change.created);
        assert!(change.updated, "a stale plugin is rewritten");
        assert_eq!(fs::read_to_string(&path).unwrap(), PLUGIN_JS);
    }

    #[test]
    fn reading_a_directory_path_errors() {
        let dir = TempDir::new().unwrap();
        // The plugin path is a directory, so reading it back fails.
        assert!(matches!(register_hook(dir.path()), Err(Error::Read { .. })));
    }

    #[test]
    fn writing_under_a_file_parent_errors() {
        let dir = TempDir::new().unwrap();
        // A regular file stands where the plugin directory would need to be.
        let blocker = dir.path().join("blocker");
        fs::write(&blocker, "x").unwrap();
        let path = blocker.join("allowlister.js");
        assert!(matches!(register_hook(&path), Err(Error::Write { .. })));
    }

    #[test]
    fn hook_command_is_the_registered_command() {
        assert_eq!(hook_command(), "allowlister hook opencode");
    }

    #[test]
    fn plugin_source_bridges_to_the_binary() {
        let src = plugin_source();
        assert!(src.contains("Bun.spawn"));
        assert!(src.contains("\"allowlister\", \"hook\", \"opencode\""));
        assert!(src.contains("decision === \"deny\""));
    }

    #[test]
    fn global_path_prefers_xdg_local_uses_cwd() {
        let env = Env {
            home: Some(PathBuf::from("/home/u")),
            xdg_config_home: Some(PathBuf::from("/xdg")),
        };
        assert_eq!(
            settings_path(true, Path::new("/proj"), &env).unwrap(),
            PathBuf::from("/xdg/opencode/plugin/allowlister.js")
        );
        assert_eq!(
            settings_path(false, Path::new("/proj"), &env).unwrap(),
            PathBuf::from("/proj/.opencode/plugin/allowlister.js")
        );
    }

    #[test]
    fn global_path_falls_back_to_home_config() {
        let env = Env {
            home: Some(PathBuf::from("/home/u")),
            xdg_config_home: None,
        };
        assert_eq!(
            settings_path(true, Path::new("/proj"), &env).unwrap(),
            PathBuf::from("/home/u/.config/opencode/plugin/allowlister.js")
        );
    }

    #[test]
    fn global_path_without_home_or_xdg_errors() {
        let env = Env {
            home: None,
            xdg_config_home: None,
        };
        assert!(matches!(
            settings_path(true, Path::new("/proj"), &env),
            Err(Error::NoConfigHome)
        ));
    }
}
